<?php

/**
 * Created by PhpStorm.
 * User: Gowtham
 * Date: 5/3/2016
 * Time: 4:59 PM
 */
class Country_model extends MY_Model
{
    protected $_table = 'country';
    protected $primary_key = 'country_id';

    protected $after_get = array('remove_sensitive_fields');
    protected $before_create = array("prop_data");
    protected $before_update = array("prop_data");

    protected function remove_sensitive_fields($data){
        unset($data->status);
        return $data;
    }

    protected function prop_data($data){
        $data['date'] = date("Y-m-d H:i:s");
        $data['user_id'] =  $this->session->userdata("user")->id;
        return $data;
    }

    function getZone(){
        $this->_table = 'zone';
        $where = func_get_args(); 
        $this->_set_where($where);
        $result =  $this->get_all();
        $this->_table = 'country';
        return $result ;
    }

    function get($primary_value)
    {
        return parent::get($primary_value); // TODO: Change the autogenerated stub
    }

    function getZoneId($primary_value){
        return $this->db->from("zone")->where('zone_id',$primary_value)->get()->row();
    }

    

}