<?php

/**
 * Created by PhpStorm.
 * User: Gowtham
 * Date: 5/5/2016
 * Time: 12:00 PM
 */
class Grade_model extends MY_Model
{
    protected $_table = 'school_grade';
    protected $primary_key = "id";
    protected $protected_attributes = array( 'id' );

    protected $after_get = array('remove_sensitive_fields');
    protected $before_create = array("prop_data");
    
    protected $join = array();
    
    function __construct() {
        parent::__construct();
        $this->join = array(
            array('school', "school.id = $this->_table.school_id" ,"school.title as school_title , school.id as school_id " )
        );
    }

    protected function remove_sensitive_fields($data){
        unset($data->date);
        unset($data->status);
        return $data;
    }

    protected function prop_data($data){
        $data['date'] = date("Y-m-d H:i:s");
        $data['user_id'] =  $this->session->userdata("user")->id;
        return $data;
    }
    
    function get_many_by()  {
        $where = func_get_args();
        $this->_database->select("$this->_table.id , $this->_table.title , $this->_table.code ");
        $this->relation_tables('school') ;
        $this->_set_where($where);
        return $this->get_all();
    }
 
    function get_school_grade_by_like($str){
        $this->_database->select("$this->_table.id , $this->_table.title  ");
        $this->relation_tables('school') ;
        $this->_database
            ->where("$this->_table.status",1)
            ->group_start()
            ->like("$this->_table.title", $str)
                ->or_group_start()
                ->like("school.title", $str)
                ->group_end()
            ->group_end();
        return $this->get_all();
    }
    
    function get_many_grade_id($values)
    {
        $this->primary_key = "$this->_table.id";
        $this->_database->select("$this->_table.id , $this->_table.title  ");
        $this->relation_tables('school') ;
        $this->_set_where(array('status',1));
        return parent::get_many($values); // TODO: Change the autogenerated stub
    }
 
}